### ISSUE TITLE
[Feature] macOS native arm64 builds

### ISSUE THREAD

**Issue by eirnym** [WerWolv/ImHex#1109]
### What feature would you like to see?

Could you please add macOS M1/M2 native builds?

### How will this feature be useful to you and others?

No need to install Rosetta 2 or every time build manually

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by eirnym** [comment]
Xcode can build universal apps even on x86_64 and since Xcode 12 it's a default behaviour

**Comment by WerWolv** [comment]
ImHex is built using GCC on macOS, we don't really use Apple's compiler or XCode at all because it's so outdated.

Of course we could still cross compile but figuring out how to do it without having access to any Mac is basically impossible. 
I'm very happy to merge pull requests adding support for this though. I just really don't want to do any more macOS debugging through GitHub Actions myself ever again lol

**Comment by eirnym** [comment]
Xcode uses clang and it's quite fresh. Older Xcode versions use older clang, obviously. 

I personally prefer clang over gcc

**Comment by eirnym** [comment]
BTW, cmake can generate Xcode project.

**Comment by eirnym** [comment]
Nevertheless, could you please keep this feature request open. I guess somebody will find a solution faster if it'd be open.

**Comment by WerWolv** [comment]
I created a new pinned issue now with this request amongst other things that I really need help with. #1111

**Comment by eirnym** [comment]
About clang/debug issue, could you explain it further? In way it's described it's very unclear, what is the problem and how to overcome it if somebody would want to look into.

**Comment by WerWolv** [comment]
I don't know how to better explain it to be honest.
We were using clang at the start which sometimes caused the build to break when I made changes. Mostly because either features weren't available yet, standard library features were implemented wrongly or differently than on other platforms, etc.
When these things happened, I always had to make a new branch, make small changes to my code, push them to github to build, wait like 20 minutes for it to fail and then continue until I found what was wrong. That was extremely frustrating. Using GCC on all platforms allows me to verify that things are correct on Windows or Linux and can simply expect them to work properly on macOS as well. 
Again, no issue if I had a mac but I don't so this is the best I can do realistically. ImHex is using very modern C++20 and C++23 features and I don't want to give up on that.

**Comment by iTrooz** [comment]
Hey, we've decided to use this issue as the "official" one for discussion about this problem.
So essentially we're going to close any other issue and point at this one

Please comment here if you have ideas to share !
(Please just comment just to say "plz do it")

**Comment by slinderud** [comment]
Note: I'm not a developer by any means. And i hardly know what I'm doing. But I got this working on my ARM mac.

Compiled following the guide here: https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macos.md
Only changed this env since it complained:
```
MACOSX_DEPLOYMENT_TARGET="11" 
```
The only issues is that signing is much stricter on arm mac, than x86. So the generated .app won't work.
https://github.com/hyperion-project/hyperion.ng/issues/1468

Worked around this by just copying the .app folder directly into `/Applications`:
```
cp -r imhex.app /Applications/
```

Hopefully this information might be a little bit useful.

I haven't actually used it much except checking if it starts

**Comment by iTrooz** [comment]
Hey ! The problem isn't so much to compile it, it is that neither of us has a M1 Mac to actually compile it.

**Comment by WerWolv** [comment]
Thanks for the help @slinderud!
The problem we're running into mostly is that we only have x86 macOS build servers available here on GitHub. That means we somehow need to cross-compile ImHex from x86_64 to ARM64. From what I've heard this is not super difficult if you just use Apple's Clang compiler but ImHex requires GCC as AppleClang lacks various features that we're using currently. 

As none of us has any Mac, it's really difficult to setup these cross-build processes without tons of trial and error using the GitHub runners. And even if we get it to compile, we have no way of verifying if the produced binary actually runs

**Comment by eirnym** [comment]
I can help with testing

**Comment by imkebe** [comment]
I can help since I was a contributor in https://github.com/hyperion-project/hyperion.ng/issues/1468

**Comment by iTrooz** [comment]
hey ! What we need is a way to build these binaries ourselves, possibly automatically. Do you think you can help with that ?

**Comment by imkebe** [comment]
The only way that would be possible from me i is to set up docker image that will be fetching code and trigger build jobs in cron like schedule and then push all results somewhere. However that would be limited to linux image.
I don't have server like hardware.

**Comment by Nemirtingas** [comment]
Hi, I don't know if you can use it for this project, but I made docker images for cross-compiling on Linux for Windows and MacOS (x86, x64, arm64) here: https://hub.docker.com/r/nemirtingas/osxcross_vcpkg
Using a cmake project should be doable.

**Comment by WerWolv** [comment]
@Nemirtingas Hey, thanks a lot for the suggesting! I tried it out but I can't seem to get vcpkg to build any libraries. The example command from your Docker hub page which installs zlib and libfmt fails with cmake throwing ` Could not find install_name_tool, please check your installation.`. Did I do something wrong?

**Comment by Nemirtingas** [comment]
I don't know, I did the following thing and it worked:
```
docker run -it --rm nemirtingas/osxcross_vcpkg:SDK11.3 bash
cat >/vcpkg/triplets/community/x64-osx-mytriplet.cmake <<EOF
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
# You can override linkage type by package if needed
if(PORT STREQUAL "portaudio")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_BUILD_TYPE release)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)

set(ENV{OSXCROSS_HOST} "x86_64-apple-$ENV{OSXCROSS_TARGET}")

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /osxcross/target/toolchain.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/osx.cmake")

set(VCPKG_C_FLAGS "-stdlib=libc++")
set(VCPKG_CXX_FLAGS "-stdlib=libc++")

EOF

vcpkg install --triplet=x64-osx-mytriplet zlib fmt
```
And it worked 🤔

**Comment by Nemirtingas** [comment]
To build for arm64 macos, I use the following triplet:
```
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)
set(ENV{OSXCROSS_HOST} "${VCPKG_OSX_ARCHITECTURES}-apple-$ENV{OSXCROSS_TARGET}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /osxcross/target/toolchain.cmake)
set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/osx.cmake")
set(VCPKG_C_FLAGS   "-stdlib=libc++ -D_LIBCPP_DISABLE_AVAILABILITY")
set(VCPKG_CXX_FLAGS "-stdlib=libc++ -D_LIBCPP_DISABLE_AVAILABILITY")
set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
```

**Comment by sambacha** [comment]
## Building for macOS 14

```bash
#!/usr/bin/env bash
CC=$(brew --prefix gcc@12)/bin/gcc-12     \
CXX=$(brew --prefix gcc@12)/bin/g++-12    \
OBJC=$(brew --prefix llvm)/bin/clang      \
OBJCXX=$(brew --prefix llvm)/bin/clang++  \
PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig" \
MACOSX_DEPLOYMENT_TARGET="14"          \
cmake                                     \
  -DCMAKE_BUILD_TYPE=Release              \
  -DCREATE_BUNDLE=ON                      \
  -DCREATE_PACKAGE=ON                     \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache      \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache    \
  -DCMAKE_OBJC_COMPILER_LAUNCHER=ccache   \
  -DCMAKE_OBJCXX_COMPILER_LAUNCHER=ccache \
  -DCMAKE_OSX_ARCHITECTURES='arm64'  \
  --fresh \
  ..
gmake -j4 package;
```

![](https://d.pr/i/IjK3pY.jpeg)

I have also used a different linker, see https://github.com/keith/ld64.lld

>**Note**      
> Additionally you can read this blog post by the author of an alt. linker, zld - https://eisel.me/lld

## Universal Binary

You can build a universal binary using both. 


>**Note**
> Here is a reference commit for actionlint showing macOS OS Compatibility matrix: https://github.com/rhysd/actionlint/pull/299/files.   
    

### Example Workflow

This is a rough example of a github action workflow using both macOS x86 and arm64:

> This contains notary as well, which is not necessary but I include it as the build artifact is a `.dmg` file and not simply some binary executable (not that it makes a difference really). 

```yaml

    release:
        name: ${{ matrix.job.target }} (${{ matrix.job.os }})
        runs-on: ${{ matrix.job.os }}
   #     needs: prepare # this can be a job that creates a changelog, tags the commit and does other pre-release tasks
    env:
      TAG: ${{ github.ref_name }}
      strategy:
          matrix:
              job:
                  # The OS is used for the runner
                  # The platform is a generic platform name
                  - os: ubuntu-20.04
                    platform: linux
                    target: x86_64-unknown-linux-gnu
                    arch: amd64
                    svm_target_platform: linux-amd64
                  - os: ubuntu-20.04
                    platform: linux
                    target: aarch64-unknown-linux-gnu
                    arch: arm64
                    svm_target_platform: linux-aarch64
                  - os: macos-11
                    platform: darwin
                    target: x86_64-apple-darwin
                    arch: amd64
                    svm_target_platform: macosx-amd64
                  - os: macos-13
                    platform: darwin
                    target: aarch64-apple-darwin
                    arch: arm64
                    svm_target_platform: macosx-aarch64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Apple Silicon setup
        if: ${{ matrix.job.target == 'aarch64-apple-darwin' }}
        run: |
            echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
            echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV

      # execute cmake build for both x86 and arm64 macOS
      # This can be a script that invokes cmake and make
      - name: Build macOS x86 and arm64
        id: macos-build
        run: bash all_macos.sh
        shell: bash

      # Currently cmake does not create a subdirectory within build with the three-word target name
      - name: Darwin link as Universal
        id: macos-link
        run: lipo -create -output ImHex-macos build/aarch64-apple-darwin/imhex-1.30.1-Darwin.dmg build/x86_64-apple-darwin/imhex-1.30.1-Darwin.dmg
        shell: bash

      # The Rest of this is optional and only needed if you want to notarize the binary
      - name: Create keychain
        run: |
          printf ${{ secrets.APPLE_P12_BASE64 }} | base64 -d > dev.p12
          security create-keychain -p "${{ secrets.APPLE_TEMPKEYCHAIN_PASSWORD }}" "${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}"
          security list-keychains -d user -s "${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}" $(security list-keychains -d user | tr -d '"')
          security set-keychain-settings "${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}"
          security import dev.p12 -k "${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}" -P "${{ secrets.APPLE_P12_PASSWORD }}" -T "/usr/bin/codesign"
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.APPLE_TEMPKEYCHAIN_PASSWORD }}" -D "${{ secrets.APPLE_CODESIGN_IDENTITY }}" -t private ${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}
          security default-keychain -d user -s ${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}
          security unlock-keychain -p ${{ secrets.APPLE_TEMPKEYCHAIN_PASSWORD }} ${{ secrets.APPLE_TEMPKEYCHAIN_NAME }}

      - name: Sign the binary
        run: |
          codesign -o runtime --timestamp -s "${{ secrets.APPLE_CODESIGN_IDENTITY }}" -v ImHex-macos
          ditto -c -k ImHex-macos ImHex-macos.zip

      - name: Notarize
        run: |
          xcrun notarytool store-credentials --apple-id janitor@github.com --password "${{ secrets.APPLE_CRED }}" --team-id "${{ secrets.APPLE_TEAMID }}" altool
          xcrun notarytool submit ImHex-macos.zip --keychain-profile altool --wait

      - name: Rename ImHex binary
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
        run: mv ImHex-macos ImHex-macos-$TAG

      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
        with:
          name: ImHex-macos-${{ env.TAG }}
          path: ImHex-macos-${{ env.TAG }}

```
