### ISSUE TITLE
Nested [[pointer_base]] result in incorrect data offsets

### ISSUE THREAD

**Issue by tcassisi** [WerWolv/ImHex#367]
Modelling a linked list of offsets that all require [[pointer_base]] fails. 

e.g.

struct Parent
{
Entry* Start : u32 [[pointer_base("calc")]];
};

struct Entry
{
   //conditional emission based on != 0 say
   Entry* Next: u32 [[pointer_base("calc")]];
};

1.  Parent okay;
2.  1st Entry - "$" shows relative offset of members, not the adjusted base. Conceptually okay but "address(this)" should be adjusted to allow for conditional emission based on read_unsigned();
3.  2nd Entry - does not work because the value passed to "calc" is wrong.

Suggestion: expose current base of the structure/union via an inbuilt function - or better might be to always adjust "address(this)"  by the base.

**Comment by tcassisi** [comment]
Still getting to grips with the source but is it possible PatternDataPointer needs to override setOffset()?

**Comment by WerWolv** [comment]
Hi! Could you post a full example to reproduce the issue? (including the calc function)
I think I identified and fixed the issue but I'd like to test it to make sure

**Comment by tcassisi** [comment]
A quick check of the nightly build with the line "if (std::mem::read_unsigned($, 4) != 0xFFFFFFFF)" then "Entry* Next:u32 [[pointer_base("calc")]]" resulted in the same "evaluation depth exceeded set limit".

It's the holidays here so should be able to upload an example next week.

**Comment by tcassisi** [comment]
Attached is a simpler example. Btw, it might be easier to see if there was an option to not throw an error on evaluation depth being exceeded but rather just stop evaluating that structure - i.e. show all the ones up to that point.

[LinkedList.zip](https://github.com/WerWolv/ImHex/files/7806673/LinkedList.zip)

Sample pattern:

```
struct THeader 
{
u16 Ignored;
u16 Offset;
} [[static]];


THeader header @0;

fn rebase1(u32 ofs)
{
  //std::print(ofs);
  return header.Offset;
};

struct TList
{
 //std::print(addressof(this));
 u16 Sequence;
 std::print(Sequence);
 if (std::mem::read_unsigned($, 2) != 0xFFFF)
   TList* Next : u16 [[pointer_base("rebase1")]];
   else
   u16 Next;
};

TList List @header.Offset;
```

**Comment by WerWolv** [comment]
Latest commit might fix this. Please let me know when you can test it out

**Comment by tcassisi** [comment]
Tested the attached sample pattern and my more complex main patterns and they're now working. Thanks.

**Comment by WerWolv** [comment]
Great thank you :)

**Comment by sad-dev** [comment]
Recursion with templates doesn't work:

You get different results with the following:

```
#include <std/io.pat>
#include <std/mem.pat>

struct THeader 
{
u16 Ignored;
u16 Offset;
} [[static]];


THeader header @0;

fn rebase1(u32 ofs)
{
  return header.Offset;
};

struct TList<auto x>
{
 //std::print("{:x}", addressof(this));
 u16 Sequence;
 std::print("{:x}", Sequence);
 if (std::mem::read_unsigned($, 2) != 0xFFFF)
   TList<x>* Next : u16 [[pointer_base("rebase1")]];
   else
   u16 Next;
};

TList<0> List @header.Offset;
```

and 
```
#include <std/io.pat>
#include <std/mem.pat>

struct THeader 
{
u16 Ignored;
u16 Offset;
} [[static]];


THeader header @0;

fn rebase1(u32 ofs)
{
  return header.Offset;
};

struct TList
{
 //std::print("{:x}", addressof(this));
 u16 Sequence;
 std::print("{:x}", Sequence);
 if (std::mem::read_unsigned($, 2) != 0xFFFF)
   TList* Next : u16 [[pointer_base("rebase1")]];
   else
   u16 Next;
};

TList List @header.Offset;
```

**Comment by sad-dev** [comment]
The cli also appears to produce incorrect output with the template pattern - one less level of recursion, and header.Ignored and header.Offset return different values.

a1.yml (With templates)
```
---
header: 
    __type: "THeader"
    __address: "0"
    __size: "4"
    __color: "#700E7FFF"
    __endian: "little"
    Ignored: 8
    Offset: 3
List: 
    __type: "TList"
    __address: "16"
    __size: "4"
    __color: "#704B568C"
    __endian: "little"
    Sequence: 65535
    Next: 
        *(Next): 
            __type: "TList"
            __address: "20"
            __size: "2"
            __color: "#70CFBE17"
            __endian: "little"
            Sequence: 52685
```

a2.yml
```
---
header: 
    __type: "THeader"
    __address: "0"
    __size: "4"
    __color: "#700E7FFF"
    __endian: "little"
    Ignored: 52685
    Offset: 52685
List: 
    __type: "TList"
    __address: "16"
    __size: "4"
    __color: "#70BD6794"
    __endian: "little"
    Sequence: 52685
    Next: 
        *(Next): 
            __type: "TList"
            __address: "20"
            __size: "4"
            __color: "#70C277E3"
            __endian: "little"
            Sequence: 52685
            Next: 
                *(Next): 
                    __type: "TList"
                    __address: "24"
                    __size: "4"
                    __color: "#70CFBE17"
                    __endian: "little"
                    Sequence: 52685
                    Next: 52685
```
